apiVersion: v1
clusters:
  - cluster:
      server: http://44.205.175.182:5002
      insecure-skip-tls-verify: true
    name: docker-desktop
contexts:
  - context:
      cluster: docker-desktop
      user: docker-desktop
    name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
  - name: docker-desktop
    user:
      token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsSTVkazlvUVdacU5ITkhTa3N0WlhRemIxcGlUakZLUzNsdloxUk5TVmh5VG5CRlFtWnliM05QT0dzaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsY0d4dmVTMWliM1F0WVdOamIzVnVkQzEwYjJ0bGJpMDViV2N5WXlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pYQnNiM2t0WW05MExXRmpZMjkxYm5RaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lJNVpqZ3lOVGcxWlMwNE5EazVMVFF4T0RRdFlXWmtNUzFpTWpjME4yTTRNbVF5WWpFaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZaR1ZtWVhWc2REcGtaWEJzYjNrdFltOTBMV0ZqWTI5MWJuUWlmUS5QdWJZTUNHa0VmVGpWMGlBTzg2d1BmdmV4QmJUT1Y1aGJsUGVBNnN1a1Y0YWUtanE2NUkxUW5HM0taV2diWExiRERQRnNqTkNUSUVkX3ljU3Zra1R1ci1ENU1SR1hvQ2JXOE1YcThyUExqRDNzeDNTZ29wRWVUdUtqclV4X05CNkRRR0JJampRRmc2THh3VGJFcWVqYWRfa1dHMExLNXd2aGFCNk5sV3BNdXM2Z1Itcmc5MERvNjZyZkpVbkMzZmNRNG1oQk80YWpBQ2RCMlZOUDc2dGRxQlJieWl1WlhhbmQzQ2xDcGhsaWJ1d3dJV2YzdEJuWkJpWUhaWjlDd1kwUm5aNkJnYVRldC1NVjJ5UXhpRFJ0NXBkZkU5QmtfNGY5dzVqUEVfdVZSeW1rX0FIdUdMbnNab2piOGxUUkNCUG9UTjdMRllINDdPMEhDb2xBSDN6Mmc=
