apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: cart-function
  name: cart-function
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cart-function
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cart-function
    spec:
      containers:
        - image: cawizca/ctse-ecommerce-cart-function:ce12923eed0827b1bd532ef2d1abc5d89787c0a1
          imagePullPolicy: Always
          name: ctse-ecommerce-cart-function
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5002
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
