apiVersion: v1
kind: Pod
metadata:
  name: cart-function
  labels:
    app: cart-function
spec:
  containers:
    - name: ctse-ecommerce-cart-function
      image: cawizca/ctse-ecommerce-cart-function:ce12923eed0827b1bd532ef2d1abc5d89787c0a1
      ports:
        - containerPort: 5002
