apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cart-function
  name: cart-function
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: cart-function
status:
  loadBalancer: {}
